# Generated by Django 6.0.6 on 2026-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='submission_text',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submission_link',
            field=models.URLField(default='https://drive.google.com/drive/home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submission_type',
            field=models.CharField(choices=[('Github', 'Github'), ('Google Drive', 'Google Drive'), ('Other', 'Other')], default='drive', max_length=50),
            preserve_default=False,
        ),
    ]
