# Generated by Django 6.0.6 on 2026-06-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Hybrid', 'Hybrid')], default='Hybrid', max_length=20),
        ),
    ]
