# Generated by Django 6.0.6 on 2026-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='room_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
