# Generated by Django 6.0.6 on 2026-06-24 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_location_alter_courses_room_no'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
