# Generated by Django 6.0.6 on 2026-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status_and_more'),
        ('courses', '0003_alter_courses_location_alter_courses_room_no'),
        ('users', '0002_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='attendance_date',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course', 'attendance_date')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('None', 'None')], default='None', max_length=10),
        ),
    ]
